services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: event-monitor-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/instagram_monitor.db:/app/instagram_monitor.db
      - ./backend/app/static/images:/app/app/static/images
      - ./backend/instaloader_session:/app/app/instaloader_session
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_BASE: /api
    container_name: event-monitor-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped
