services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: event-monitor-backend
    ports:
      - "8000:8000"
    volumes:
      - event-monitor-db:/app/instagram_monitor.db
      - event-monitor-images:/app/app/static/images
      - event-monitor-session:/app/app/instaloader_session
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_BASE: /api
    container_name: event-monitor-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  event-monitor-db:
  event-monitor-images:
  event-monitor-session:
